version: '3.8'

services:
  db:
    image: postgres:14
    container_name: nic_shop_db_container
    restart: always
    environment:
      POSTGRES_DB: nic_shop_db
      POSTGRES_USER: nic_shop_user
      POSTGRES_PASSWORD: nic_shop_password
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nic_shop_db
      SPRING_DATASOURCE_USERNAME: nic_shop_user
      SPRING_DATASOURCE_PASSWORD: nic_shop_password
    ports:
      - "8080:8080"

volumes:
  db_data:
