jwt:
  secret: changemeafterdeploysecretkey1234567891011121314151617181920212223242252627282930
  lifetime: 30m
  refresh_lifetime: 30d
server:
  port: 8080
spring:
  application:
    name: nic-shop-task
  datasource:
    # for developing, wait 210s every rebuild is too long
#    url: jdbc:postgresql://localhost:5432/nic_shop
#    username: postgres
#    password: admin
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: officialsportgram@gmail.com
    password: "vipl idnr huuo fogv"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  profiles:
    active: default

file:
  files-dir: /app/images/
  files-sep: /

